### PR TITLE
Fix icons on MSVC and remove deprecated function 

### PR DESCRIPTION
**Pull request by markreidvfx**
Here are some small fixes. The icons don't work at all for me when I compile with MSVC.  
before_crop
MSVC doesn't seem to like the Universal character `\U` encoding in strings. There are multiple ways to handle this issue

https://learn.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=msvc-170

I choose to use hex encoding, I think its the most portable and supports the most C++ versions.  Another option that worked for me was using `u8` literal prefixes, but I think that would require C++20 or greater. 

I'm not sure if it was intentional but "+Track" text was getting lost, I merged the fonts to solve this issue. This allows the icon font use text too.

fixed_crop

Also I've been experimenting with upgrading IMGUI to the latest version and `ImGui::GetContentRegionAvailWidth()` has been removed. The docs say to use `ImGui::GetContentRegionAvail().x` instead.

### CODE REVIEW

**Comment by jminor** [comment]
Nice!

It might be nice to embed the font inside the application to avoid carrying around a separate font file. Dear ImGui comes with a utility `binary_to_compressed_c` for this purpose. I did that in a different project with these pieces:

```
add_custom_command(
    OUTPUT "${PROJECT_SOURCE_DIR}/embedded_font.inc"
    COMMAND binary_to_compressed_c -base85 "${PROJECT_SOURCE_DIR}/fonts/Shure Tech Mono Nerd Font Complete Mono.ttf" ShureTechMono > ${PROJECT_SOURCE_DIR}/embedded_font.inc
    COMMENT "Embedding font..."
    MAIN_DEPENDENCY "fonts/Shure Tech Mono Nerd Font Complete.ttf"
    VERBATIM)
```

and

```
    gFont = io.Fonts->AddFontFromMemoryCompressedBase85TTF(
        ShureTechMono_compressed_data_base85,
        20.0f);

    static const ImWchar icon_fa_ranges[] = {
        // 0x0000, 0x00FF, // ASCII
        0xe5fa, 0xe631, // Seti-UI + Custom
        0xe700, 0xe7c5, // Devicons
        0xf000, 0xf2e0, // Font Awesome
        0xe200, 0xe2a9, // Font Awesome Extension
        0xf500, 0xfd46, // Material Design Icons
        0xe300, 0xe3eb, // Weather
        0xf400, 0xf4a9, // Octicons (1)
        0x2665, 0x2665, // Octicons (2)
        0x26A1, 0x26A1, // Octicons (3)
        0xe0a0, 0xe0a2, // Powerline Symbols (1)
        0xe0b0, 0xe0b3, // Powerline Symbols (2)
        0xe0a3, 0xe0a3, // Powerline Extra Symbols (1)
        0xe0b4, 0xe0c8, // Powerline Extra Symbols (2)
        0xe0ca, 0xe0ca, // Powerline Extra Symbols (3)
        0xe0cc, 0xe0d4, // Powerline Extra Symbols (4)
        0x23fb, 0x23fe, //2b58 // IEC Power Symbols
        0xf300, 0xf32d, // Font Logos
        0xe000, 0xe00a, // Pomicons
        0xea60, 0xebeb, // Codicons
        0
    };

    ImFontConfig config;
    config.MergeMode = true;
    config.GlyphOffset.x = 1.0f;
    config.GlyphOffset.y = 1.5f;
    io.Fonts->AddFontFromMemoryCompressedBase85TTF(
        ShureTechMono_compressed_data_base85,
        30.0f,
        &config,
        icon_fa_ranges);
```

and one of these fonts: https://www.nerdfonts.com/font-downloads
We probably don't need *all* those icons, but it's easier to bring them in than to curate the specific ones we want.

Maybe I can do that step after we land this PR?

**Comment by markreidvfx** [comment]
I've done the same thing in the past.  Embedding the would be handy.  Raven currently crashes if you build it in debug and it can't find a font because of a debug assert in imgui,  it is a minor annoyance.

**Comment by jminor** [comment]
Thanks! I'll try the embedding thing next - and maybe pick a less nerdy font ;)

**Comment by jminor** [comment]
Embedding is working now. Can you try on Windows to see if it works there?

Also, how did you convert `\uF014` to `\xef\x80\x94`?

**Comment by markreidvfx** [comment]
Awesome, I'll give it a go!

I did the conversion in python
```python
print("\uF014".encode("utf-8"))
```

**Comment by meshula** [comment]
That font assert in Dear ImGui is really annoying ~ one has to test for the existence of the font file before letting Dear have a go.

**Comment by markreidvfx** [comment]
No problems on windows, worked like a charm!

**Pull request merged**
